image:
  file: .gitpod.Dockerfile

ports:
  - port: 5432
    onOpen: ignore
    description: "PostgreSQL Database"
    name: "PostgreSQL"
  - port: 3000
    onOpen: open-browser
    description: "Application"
    name: "Application"
  

tasks:
  - name: Start app
    init: npm install
    command: docker-compose up